Unit test
Chalyan/SICP pull request #5
Opened 2021-11-08 14:22 UTC by Chalyan

2021-11-12 13:34 UTC, amuradyan requested changes
Awesome!!!!

2021-11-12 13:34 UTC, amuradyan commented on Building_abstractions_with_procedures/The_elements_of_programming/Procedures_as_Black_Box_Abstractions/cube_root_with_lexical_scoping/function_module.scm
> +    (define (cube x)
Please, add tests for this method.

2021-11-12 13:34 UTC, amuradyan commented on Building_abstractions_with_procedures/The_elements_of_programming/Procedures_as_Black_Box_Abstractions/cube_root_with_lexical_scoping/function_module.scm
> +    (define (square x)
Please, add tests for `square` method.

2021-11-13 13:11 UTC, Chalyan commented on Building_abstractions_with_procedures/The_elements_of_programming/Procedures_as_Black_Box_Abstractions/cube_root_with_lexical_scoping/function_module.scm
> +    (define (square x)
Added all needed tests for both 'square' and 'cube' functions. Please recheck.

2021-11-16 14:09 UTC, amuradyan commented
Please, update the PR title, to make it more descriptive.

2021-11-16 14:21 UTC, amuradyan approved these changes
lgtm

2021-11-16 19:30 UTC, merged